### ISSUE TITLE
Recipe Ordering?

### ISSUE THREAD

**Issue by jennank** [bernardopacini/ReadTheRecipe#6]
This is more a general formatting question. In the meat category, do we want to stick with strictly alphabetical? Or should we separate by meat type as well (same goes for the seafood section)? i.e. should all chicken recipes be lumped together, all pork recipes together, etc.?

**Comment by bernardopacini** [comment]
Hmm, if we separate them out by topic can we put header instead of implying there is a separation without actually making it clear? I do like the idea of separating by type of meat, although will there ever be a situation where we have multiple meats in the same recipe?

**Comment by jennank** [comment]
I think it would be nice to keep them in separate categories if possible. It gets complicated with the mixed meats, but I can't come up with anything off the top of my head (that wouldn't fall into the pasta or breakfast category). Do you have a recipe in mind that would cause this overlap problem?

**Comment by jennank** [comment]
Resolved. Sub-headings added for the meat category
